scalar Int32

type Query {
  hello: String!
}

type Mutation {
  loginResponse(input: LoginRequestInput!): LoginPayload!
  socialLoginResponse(input: SocialLoginRequestInput!): LoginPayload!
  signUpResponse(input: SignUpRequestInput!): ResponseModel!
  verifyOtpResponse(input: VerifyOtpRequestInput!): LoginPayload!
  forgotPasswordResponse(input: ForgotPasswordRequestInput!): ResponseModel!
  verifyOtpForResetPasswordResponse(
    input: VerifyOtpForResetPasswordRequestInput!
  ): ResponseModel!
  resetPasswordResponse(input: ResetPasswordRequestInput!): ResponseModel!
  status(input: ChangeStatusRequestInput!): ResponseModel!
}

input LoginRequestInput {
  email: String!
  password: String!
}

input SignUpRequestInput {
  username: String!
  email: String!
  password: String!
}

input VerifyOtpRequestInput {
  otp: String!
  username: String!
  email: String!
  password: String!
  googleId: String!
  appleId: String!
}

type LoginPayload {
  status: Boolean!
  message: String!
  data: LoginResponse!
}

type LoginResponse {
  challengeStartDate: String!
  challenges: [Challenge!]!
  user: User!
}

type Challenge {
  id: ID!
  level: Int!
  day: Int!
  date: String!
  completedTasks: [String!]!
  status: String!
}

type User {
  id: ID!
  email: String!
  userName: String!
  token: String!
}

type SignUpPayload {
  status: Boolean!
  message: String!
  loginResponse: LoginResponse!
}

type ResponseModel {
  status: Boolean!
  message: String!
}

input ForgotPasswordRequestInput {
  email: String!
}

input VerifyOtpForResetPasswordRequestInput {
  email: String!
  otp: String!
}

input ResetPasswordRequestInput {
  email: String!
  newPassword: String!
  confirmPassword: String!
}

input SocialLoginRequestInput {
  socialId: String!
  type: String!
  email: String
  name: String!
}

input ChangeStatusRequestInput {
  status: String!
  challengeId: ID!
}
