type Query {
  hello: String!
}

type Mutation {
  login(input: LoginRequestInput!): LoginResponse!
  socialLogin(input: SocialLoginRequestInput!): LoginResponse!
  signup(input: SignUpRequestInput!): User!
  verifyOtp(input: VerifyOtpRequestInput!): LoginResponse!
  forgotPassword(input: ForgotPasswordRequestInput!): User!
  verifyOtpForResetPassword(
    input: VerifyOtpForResetPasswordRequestInput!
  ): User!
  resetPassword(input: ResetPasswordRequestInput!): User!
  completeTask(userId: ID!, input: ChangeStatusRequestInput!): Challenge!
  selfCareForm(input: SelfCareFormRequestInput!): SelfCareReponse!
  selfCareFormData(
    userId: ID!
    input: GetSelfCareFormRequestInput!
  ): SelfCareReponse!
}

type LoginResponse {
  user: User!
  challengeStartDate: String!
  challenges: [Challenge!]!
}

input VerifyOtpRequestInput {
  otp: String!
  username: String!
  email: String!
  password: String!
}

type Challenge {
  id: ID!
  userId: ID!
  level: Int!
  day: Int!
  date: String!
  completedTasks: [String!]!
  status: String!
}

type User {
  id: ID!
  email: String!
  userName: String!
  token: String!
}

input LoginRequestInput {
  email: String!
  password: String!
}

input SignUpRequestInput {
  email: String!
}

input ForgotPasswordRequestInput {
  email: String!
}

input VerifyOtpForResetPasswordRequestInput {
  email: String!
  otp: String!
}

input ResetPasswordRequestInput {
  email: String!
  newPassword: String!
  confirmPassword: String!
}

input SocialLoginRequestInput {
  socialId: String!
  type: String!
  email: String
  name: String!
}

input ChangeStatusRequestInput {
  level: Int!
  day: Int!
  completedTask: String!
  date: String!
}

input SelfCareFormRequestInput {
  challengeId: ID!
  ownStatement: String!
  thingsYouWillDoTodayToNutureYourself: String!
  thingsThatYouLoveAboutYourself: String!
  thingsTodayThatBringYouJoyAndFlow: String!
}

input GetSelfCareFormRequestInput {
  day: Int!
  level: Int!
}

type SelfCareReponse {
  id: ID!
  ownStatement: String!
  thingsYouWillDoTodayToNutureYourself: String!
  thingsThatYouLoveAboutYourself: String!
  thingsTodayThatBringYouJoyAndFlow: String!
}
