type Mutation {
  loginResponse(input: LoginRequestInput!): LoginPayload!
  signUpResponse(input: SignUpRequestInput!): ResponseModel!
  verifyOtpResponse(input: VerifyOtpRequestInput!): LoginPayload!
  forgotPasswordResponse(input: ForgotPasswordRequestInput!): ResponseModel!
  verifyOtpForResetPasswordResponse(
    input: VerifyOtpForResetPasswordRequestInput!
  ): ResponseModel!
  resetPasswordResponse(input: ResetPasswordRequestInput!): ResponseModel!
}

input LoginRequestInput {
  email: String!
  password: String!
}

input SignUpRequestInput {
  username: String!
  email: String!
  password: String!
}

input VerifyOtpRequestInput {
  otp: String!
  username: String!
  email: String!
  password: String!
}

type LoginPayload {
  status: Boolean!
  message: String!
  loginResponse: LoginResponse!
}

type LoginResponse {
  id: ID!
  username: String!
  email: String!
  Token: String!
}

type SignUpPayload {
  status: Boolean!
  message: String!
  loginResponse: LoginResponse!
}

type ResponseModel {
  status: Boolean!
  message: String!
}

input ForgotPasswordRequestInput {
  email: String!
}

input VerifyOtpForResetPasswordRequestInput {
  email: String!
  otp: String!
}

input ResetPasswordRequestInput {
  email: String!
  newPassword: String!
  confirmPassword: String!
}
