package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"challenge/graph/model"
	"challenge/handlers/auth"
	"context"
	"fmt"
)

// LoginRequest is the resolver for the loginRequest field.
func (r *mutationResolver) LoginRequest(ctx context.Context, input model.LoginRequestInput) (*model.LoginPayload, error) {
	return auth.LoginCustomer(ctx, r.DB, input), nil
}

// SignUpRequest is the resolver for the signUpRequest field.
func (r *mutationResolver) SignUpRequest(ctx context.Context, input model.SignUpRequestInput) (*model.ResponseModel, error) {
	return auth.SignUpUser(ctx, r.DB, input, r.SESClient), nil
}

// VerifyOtpRequest is the resolver for the verifyOtpRequest field.
func (r *mutationResolver) VerifyOtpRequest(ctx context.Context, input model.VerifyOtpRequestInput) (*model.LoginPayload, error) {
	return auth.VerifyOtp(ctx, r.DB, input), nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
