package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"challenge/graph/model"
	"challenge/handlers/auth"
	"context"
	"fmt"
)

// LoginResponse is the resolver for the loginResponse field.
func (r *mutationResolver) LoginResponse(ctx context.Context, input model.LoginRequestInput) (*model.LoginPayload, error) {
	return auth.LoginCustomer(ctx, r.DB, input), nil
}

// SocialLoginResponse is the resolver for the socialLoginResponse field.
func (r *mutationResolver) SocialLoginResponse(ctx context.Context, input model.SocialLoginRequestInput) (*model.LoginPayload, error) {
	return auth.SocialLoginCustomer(ctx, r.DB, input), nil
}

// SignUpResponse is the resolver for the signUpResponse field.
func (r *mutationResolver) SignUpResponse(ctx context.Context, input model.SignUpRequestInput) (*model.ResponseModel, error) {
	return auth.SignUpUser(ctx, r.DB, r.SESClient, input), nil
}

// VerifyOtpResponse is the resolver for the verifyOtpResponse field.
func (r *mutationResolver) VerifyOtpResponse(ctx context.Context, input model.VerifyOtpRequestInput) (*model.LoginPayload, error) {
	return auth.VerifyOtp(ctx, r.DB, input), nil
}

// ForgotPasswordResponse is the resolver for the forgotPasswordResponse field.
func (r *mutationResolver) ForgotPasswordResponse(ctx context.Context, input model.ForgotPasswordRequestInput) (*model.ResponseModel, error) {
	return auth.ForgotPassword(ctx, r.DB, r.SESClient, input), nil
}

// VerifyOtpForResetPasswordResponse is the resolver for the verifyOtpForResetPasswordResponse field.
func (r *mutationResolver) VerifyOtpForResetPasswordResponse(ctx context.Context, input model.VerifyOtpForResetPasswordRequestInput) (*model.ResponseModel, error) {
	return auth.VerifyOtpForResetPassword(ctx, r.DB, input), nil
}

// ResetPasswordResponse is the resolver for the resetPasswordResponse field.
func (r *mutationResolver) ResetPasswordResponse(ctx context.Context, input model.ResetPasswordRequestInput) (*model.ResponseModel, error) {
	return auth.ResetPassword(ctx, r.DB, input), nil
}

// Status is the resolver for the status field.
func (r *mutationResolver) Status(ctx context.Context, input model.ChangeStatusRequestInput) (*model.ResponseModel, error) {
	return auth.ChangeStatus(ctx, r.DB, input), nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
