package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"challenge/graph/model"
	"challenge/handlers/auth"
	"context"
	"fmt"

	"github.com/gofiber/fiber/v2"
		jtoken "github.com/golang-jwt/jwt/v4"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequestInput) (*model.LoginResponse, error) {
	loginPayload, err := auth.LoginCustomer(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return loginPayload, nil
}

// SocialLogin is the resolver for the socialLogin field.
func (r *mutationResolver) SocialLogin(ctx context.Context, input model.SocialLoginRequestInput) (*model.LoginResponse, error) {
	socialLoginPayload, err := auth.SocialLoginCustomer(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return socialLoginPayload, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignUpRequestInput) (*model.User, error) {
	signupPayload, err := auth.SignUpUser(ctx, r.DB, r.SESClient, input)
	if err != nil {
		return nil, err
	}
	return signupPayload, nil
}

// VerifyOtp is the resolver for the verifyOtp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, input model.VerifyOtpRequestInput) (*model.LoginResponse, error) {
	signupPayload, err := auth.VerifyOtp(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return signupPayload, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPasswordRequestInput) (*model.User, error) {
	ForgotPasswordPayload, err := auth.ForgotPassword(ctx, r.DB, r.SESClient, input)
	if err != nil {
		return nil, err
	}
	return ForgotPasswordPayload, nil
}

// VerifyOtpForResetPassword is the resolver for the verifyOtpForResetPassword field.
func (r *mutationResolver) VerifyOtpForResetPassword(ctx context.Context, input model.VerifyOtpForResetPasswordRequestInput) (*model.User, error) {
	VerifyOtpPayload, err := auth.VerifyOtpForResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return VerifyOtpPayload, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordRequestInput) (*model.User, error) {
	resetPasswordPayload, err := auth.ResetPassword(ctx, r.DB, input)
	if err != nil {
		return nil, err
	}
	return resetPasswordPayload, nil
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, userID string, input model.ChangeStatusRequestInput) (*model.Challenge, error) {
	
	changeStatusPayload, err := auth.CompleteTask(ctx, r.DB, userID, input)
	if err != nil {
		return nil, err
	}
	return changeStatusPayload, nil
}

// SelfCareForm is the resolver for the selfCareForm field.
func (r *mutationResolver) SelfCareForm(ctx context.Context, input model.SelfCareFormRequestInput) (*model.SelfCareReponse, error) {
	deviceID, err := extractDeviceIDFromToken(ctx)
	if err != nil {
		return nil, err
	}

	selfCarePayload, err := auth.SelfCareForm(ctx, r.DB, deviceID, input)
	if err != nil {
		return nil, err
	}
	return selfCarePayload, nil
}

// SelfCareFormData is the resolver for the selfCareFormData field.
func (r *mutationResolver) SelfCareFormData(ctx context.Context, userID string, input model.GetSelfCareFormRequestInput) (*model.SelfCareReponse, error) {
	selfCareFormDataPayload, err := auth.GetSelfCareFormData(ctx, r.DB, userID, input)
	if err != nil {
		return nil, err
	}
	return selfCareFormDataPayload, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func extractDeviceIDFromToken(ctx context.Context) (string, error) {
	token := ctx.Value("user").(*jtoken.Token)
	claims, ok := token.Claims.(jtoken.MapClaims)
	if !ok {
		return "", fiber.NewError(fiber.StatusInternalServerError, "Failed to parse token claims")
	}
	deviceID, ok := claims["deviceId"].(string)
	if !ok {
		return "", fiber.NewError(fiber.StatusInternalServerError, "DeviceId not found in token claims")
	}
	return deviceID, nil
}
