// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ForgotPasswordRequestInput struct {
	Email string `json:"email"`
}

type LoginPayload struct {
	Status        bool           `json:"status"`
	Message       string         `json:"message"`
	LoginResponse *LoginResponse `json:"loginResponse"`
}

type LoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Token         string         `json:"token"`
	SocialDetails *SocialDetails `json:"socialDetails"`
}

type Mutation struct {
}

type Query struct {
}

type ResetPasswordRequestInput struct {
	Email           string `json:"email"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type ResponseModel struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
}

type SignUpPayload struct {
	Status        bool           `json:"status"`
	Message       string         `json:"message"`
	LoginResponse *LoginResponse `json:"loginResponse"`
}

type SignUpRequestInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SocialDetails struct {
	AppleID  *string `json:"appleId,omitempty"`
	GoogleID *string `json:"googleId,omitempty"`
}

type SocialLoginRequestInput struct {
	SocialID string  `json:"socialId"`
	Type     string  `json:"type"`
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
}

type VerifyOtpForResetPasswordRequestInput struct {
	Email string `json:"email"`
	Otp   string `json:"otp"`
}

type VerifyOtpRequestInput struct {
	Otp      string `json:"otp"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	GoogleID string `json:"googleId"`
	AppleID  string `json:"appleId"`
}
