// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Challenge struct {
	ID             string   `json:"id"`
	UserID         string   `json:"userId"`
	Level          int      `json:"level"`
	Day            int      `json:"day"`
	Date           string   `json:"date"`
	CompletedTasks []string `json:"completedTasks"`
	Status         string   `json:"status"`
}

type ChangeStatusRequestInput struct {
	Status      string `json:"status"`
	ChallengeID string `json:"challengeId"`
}

type ForgotPasswordRequestInput struct {
	Email string `json:"email"`
}

type GetSelfCareFormRequestInput struct {
	Day   int `json:"day"`
	Level int `json:"level"`
}

type LoginRequestInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User               *User        `json:"user"`
	ChallengeStartDate string       `json:"challengeStartDate"`
	Challenges         []*Challenge `json:"challenges"`
}

type Mutation struct {
}

type Query struct {
}

type ResetPasswordRequestInput struct {
	Email           string `json:"email"`
	NewPassword     string `json:"newPassword"`
	ConfirmPassword string `json:"confirmPassword"`
}

type SelfCareFormRequestInput struct {
	ChallengeID                          string `json:"challengeId"`
	OwnStatement                         string `json:"ownStatement"`
	ThingsYouWillDoTodayToNutureYourself string `json:"thingsYouWillDoTodayToNutureYourself"`
	ThingsThatYouLoveAboutYourself       string `json:"thingsThatYouLoveAboutYourself"`
	ThingsTodayThatBringYouJoyAndFlow    string `json:"thingsTodayThatBringYouJoyAndFlow"`
}

type SelfCareReponse struct {
	ID                                   string `json:"id"`
	OwnStatement                         string `json:"ownStatement"`
	ThingsYouWillDoTodayToNutureYourself string `json:"thingsYouWillDoTodayToNutureYourself"`
	ThingsThatYouLoveAboutYourself       string `json:"thingsThatYouLoveAboutYourself"`
	ThingsTodayThatBringYouJoyAndFlow    string `json:"thingsTodayThatBringYouJoyAndFlow"`
}

type SignUpRequestInput struct {
	Email string `json:"email"`
}

type SocialLoginRequestInput struct {
	SocialID string  `json:"socialId"`
	Type     string  `json:"type"`
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
}

type TaskInput struct {
	Level          int      `json:"level"`
	Day            int      `json:"day"`
	Date           string   `json:"date"`
	CompletedTasks []string `json:"completedTasks"`
	Status         string   `json:"status"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	UserName string `json:"userName"`
	Token    string `json:"token"`
}

type UserReq struct {
	Otp      string `json:"otp"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	GoogleID string `json:"googleId"`
	AppleID  string `json:"appleId"`
}

type VerifyOtpForResetPasswordRequestInput struct {
	Email string `json:"email"`
	Otp   string `json:"otp"`
}

type VerifyOtpRequestInput struct {
	User               *UserReq   `json:"user"`
	ChallengeStartDate string     `json:"challengeStartDate"`
	Task               *TaskInput `json:"task"`
}
